title: Parthasarathi D
logo: Partha.jpg
description: linkedin.com/Parthasarathi D
description: d.parthasarathi07@gmail.com
description: +918825835514

description: C ++ C C# PYTHON HTML/CSS JAVA JAVASCRIPT JSP JSF PHP SQL 
description: OS DBMS OOPS DATA STRUCTURES ALGORITHM ANALYSIS
show_downloads: false
theme: jekyll-theme-minimal
