title: Parthasarathi D
logo: IMG_1630-modified.png
description: linkedin.com/Parthasarathi D
d.parthasarathi07@gmail.com
+918825835514

C ++ C C# PYTHON HTML/CSS JAVA JAVASCRIPT JSP JSF PHP SQL 
show_downloads: false
theme: jekyll-theme-minimal
