title: Parthasarathi D
logo: partha.jpg
description: 
linkedin.com/Parthasarathi D
d.parthasarathi07@gmail.com
+918825835514

C ++ C C# PYTHON HTML/CSS JAVA JAVASCRIPT JSP JSF PHP SQL 
OS DBMS OOPS DATA STRUCTURES ALGORITHM ANALYSIS
show_downloads: false
theme: jekyll-theme-minimal
